In [21]:
from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd
import datetime
import numpy as np

In [16]:
companies_dict = {
'Amazon': 'AMZN',
'Apple': 'AAPL',
'Walgreen': 'WBA',
'Northrop Grumman': 'NOC',
'Boeing': 'BA',
'Lockheed Martin': 'LMT',
'McDonalds': 'MCD',
'Intel': 'INTC',
'Navistar': 'NAV',  
'IBM': 'IBM',
'Texas Instruments': 'TXN',
'MasterCard': 'MA',
'Microsoft': 'MSFT',
'General Electrics': 'GE',
'Symantec': 'SYMC',
'American Express': 'AXP',
'Pepsi': 'PEP',
'Coca Cola': 'KO',
'Johnson & Johnson': 'JNJ',
'Toyota': 'TM',
'Honda': 'HMC',
'Sony': 'SNE',
'Exxon': 'XOM',
'Chevron': 'CVX',
'Valero Energy': 'VLO',
'Ford': 'F',
'Bank of America': 'BAC'}

#sort the dictionary by stock labels
companies = sorted(companies_dict.items(), key=lambda x:x[1])
#define the datasource to use
data_source = "iex"
#define the start and end dates
start_date = "2017-12-31"
end_date = "2019-03-29"
#use pandas_reader.data.DataReader
data_list = []
for item in companies_dict.values():
    data_list.append(data.DataReader(item, data_source, start_date, end_date))

In [19]:
#calculating stock movement
for d in data_list:
    d["movement"] = d["close"] - d["open"]
data_list[0]

               open     high      low    close    volume  movement
date
2018-01-02  1172.00  1190.00  1170.51  1189.01   2694494     17.01
2018-01-03  1188.30  1205.49  1188.30  1204.20   3108793     15.90
2018-01-04  1205.00  1215.87  1204.66  1209.59   3022089      4.59
2018-01-05  1217.51  1229.14  1210.00  1229.14   3544743     11.63
2018-01-08  1236.00  1253.08  1232.03  1246.87   4279475     10.87
2018-01-09  1256.90  1259.33  1241.76  1252.70   3661316     -4.20
2018-01-10  1245.15  1254.33  1237.23  1254.33   2686017      9.18
2018-01-11  1259.74  1276.77  1256.46  1276.68   3125048     16.94
2018-01-12  1273.39  1305.76  1273.39  1305.20   5443730     31.81
2018-01-16  1323.00  1339.94  1292.30  1304.86   7220701    -18.14
2018-01-17  1312.24  1314.00  1280.88  1295.00   5253754    -17.24
2018-01-18  1293.95  1304.60  1284.02  1293.32   4026915     -0.63
2018-01-19  1312.00  1313.00  1292.99  1294.58   4578536    -17.42
2018-01-22  1297.17  1327.45  1296.66  1327.31   4140061     30.14
2018-01-23  1338.09  1364.90  1337.34  1362.54   5169306     24.45
2018-01-24  1374.82  1388.16  1338.00  1357.51   6807457    -17.31
2018-01-25  1368.00  1378.34  1357.62  1377.95   4753012      9.95
2018-01-26  1392.01  1402.53  1380.91  1402.05   4857310     10.04
2018-01-29  1409.18  1431.39  1400.44  1417.68   5701898      8.50
2018-01-30  1403.17  1439.25  1392.00  1437.82   5871942     34.65
2018-01-31  1451.30  1472.58  1450.04  1450.89   6424693     -0.41
2018-02-01  1445.00  1459.88  1385.14  1390.00   9113808    -55.00
2018-02-02  1477.39  1498.00  1414.00  1429.95  11125722    -47.44
2018-02-05  1402.62  1458.98  1320.72  1390.00  11494985    -12.62
2018-02-06  1361.46  1443.99  1351.79  1442.84  11066819     81.38
2018-02-07  1449.00  1460.99  1415.15  1416.78   7162741    -32.22
2018-02-08  1429.67  1433.75  1349.94  1350.50   8578557    -79.17
2018-02-09  1373.49  1383.50  1265.93  1339.60  14141524    -33.89
2018-02-12  1364.67  1393.81  1344.01  1386.23   6738944     21.56
2018-02-13  1385.93  1419.72  1383.53  1414.51   5917879     28.58
...             ...      ...      ...      ...       ...       ...
2019-02-15  1627.86  1628.91  1604.50  1607.95   4343893    -19.91
2019-02-19  1601.00  1634.00  1600.56  1627.58   3681656     26.58
2019-02-20  1630.00  1634.93  1610.12  1622.10   3337589     -7.90
2019-02-21  1619.85  1623.56  1600.91  1619.44   3483392     -0.41
2019-02-22  1623.50  1634.94  1621.17  1631.56   3096191      8.06
2019-02-25  1641.45  1654.60  1630.39  1633.00   3184462     -8.45
2019-02-26  1625.98  1639.99  1616.13  1636.40   2665815     10.42
2019-02-27  1628.18  1641.81  1615.10  1641.09   3148824     12.91
2019-02-28  1635.25  1651.77  1633.83  1639.83   3025891      4.58
2019-03-01  1655.13  1674.26  1651.00  1671.73   4974877     16.60
2019-03-04  1685.00  1709.43  1674.36  1696.17   6167358     11.17
2019-03-05  1702.95  1707.80  1689.01  1692.43   3681522    -10.52
2019-03-06  1695.97  1697.75  1668.28  1668.95   3996001    -27.02
2019-03-07  1667.37  1669.75  1620.51  1625.95   4957017    -41.42
2019-03-08  1604.01  1622.72  1586.57  1620.80   4667014     16.79
2019-03-11  1626.12  1672.29  1626.01  1670.62   3876352     44.50
2019-03-12  1669.00  1684.27  1660.98  1673.10   3614498      4.10
2019-03-13  1683.00  1700.00  1679.35  1690.81   3552041      7.81
2019-03-14  1691.20  1702.00  1684.34  1686.22   2946618     -4.98
2019-03-15  1703.00  1718.80  1693.13  1712.36   7550870      9.36
2019-03-18  1712.70  1750.00  1712.63  1742.15   5429058     29.45
2019-03-19  1753.51  1784.16  1753.51  1761.85   6364161      8.34
2019-03-20  1769.94  1799.50  1767.03  1797.27   6265633     27.33
2019-03-21  1796.26  1823.75  1787.28  1819.26   5767797     23.00
2019-03-22  1810.17  1818.98  1763.11  1764.77   6362983    -45.40
2019-03-25  1757.79  1782.68  1747.50  1774.26   5103803     16.47
2019-03-26  1793.00  1805.77  1773.36  1783.76   4865880     -9.24
2019-03-27  1784.13  1787.50  1745.68  1765.70   4324801    -18.43
2019-03-28  1770.00  1777.93  1753.47  1773.42   3042958      3.42
2019-03-29  1786.58  1792.86  1776.63  1780.75   3320793     -5.83

[312 rows x 6 columns]

In [22]:
#Put all of the data into a matrix
X = []
for d in data_list:
    X.append(d["movement"])
X = np.array(X)
X

array([[ 17.01  ,  15.9   ,   4.59  , ..., -18.43  ,   3.42  ,  -5.83  ],
       [  2.0601,  -0.2943,   0.4807, ...,  -0.28  ,  -0.23  ,   0.12  ],
       [  1.621 ,   0.4077,  -1.8346, ...,   0.53  ,   0.17  ,   0.52  ],
       ...,
       [  0.584 ,   0.6798,   0.1724, ...,  -0.43  ,  -0.73  ,  -0.77  ],
       [  0.1264,   0.0722,   0.1805, ...,  -0.1279,   0.1181,  -0.0197],
       [  0.1466,  -0.0977,   0.215 , ...,  -0.06  ,   0.13  ,   0.04  ]])

In [ ]:
#building a pipeline
from sklearn.pipeline import make_pipeline
from sklearn.cluster import KMeans
from sklearn.preprocessing import Normalizer